//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plants
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plants()
        {
            this.ProjectPlants = new HashSet<ProjectPlants>();
        }
    
        public int IDPlant { get; set; }
        public string PlantName { get; set; }
        public int IDPlantSpecies { get; set; }
        public string PlantInfo { get; set; }
        public Nullable<double> WidthPlant { get; set; }
        public Nullable<double> HeightPlant { get; set; }
        public string PicturePlant { get; set; }
        public string PicturePlantTop { get; set; }
    
        public virtual PlantSpecies PlantSpecies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectPlants> ProjectPlants { get; set; }
    }
}
