//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectStructure
    {
        public int IDProjectStructure { get; set; }
        public int IDProject { get; set; }
        public int IDStructure { get; set; }
        public double WidthStructure { get; set; }
        public double HeightStructure { get; set; }
        public double PointX { get; set; }
        public double PointY { get; set; }
    
        public virtual Projects Projects { get; set; }
        public virtual Structures Structures { get; set; }
    }
}
